name = "vite-react-example"
compatibility_date = "2024-03-12"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add any environment variables here if needed 

[site]
bucket = "./dist"

[build]
command = "npm run build"
watch_dir = "src" 